### ISSUE TITLE
Failed to Compile w/ Absolute Import Paths v1.2.0

### ISSUE THREAD

**Issue by marciandmnd** [creativetimofficial/material-dashboard-react#20] opened 2018-04-21 19:06 UTC
Hi,

I followed the quick start and terminal commands instructions from the Readme and am getting a failed to compile error due modules being unable to resolve. When I change the import statements to use relative paths the modules do resolve:

For example, with absolute path:
`import "assets/css/material-dashboard-react.css?v=1.2.0"; // Compile Error`

Changing to relative path:
`import "./assets/css/material-dashboard-react.css?v=1.2.0"; // Module is resolved properly`

![screenshot from 2018-04-21 12-01-45](https://user-images.githubusercontent.com/5395890/39087839-db49a60e-455b-11e8-9928-dea5b12d0889.png)

I saw the `.env` file does specify the `NODE_PATH` environment variable, but cannot get absolute paths to work on import statements; 

Thanks!

**Comment by EINazare** [comment] 2018-04-24 05:54
Hello @marciandmnd ,

You can solve this issue by changing the start script from:
```
"start": "react-scripts start",
```
to
```
"start": "NODE_PATH=./src react-scripts start",
```
and also you will need to install cross-env globally on your machine
```
npm install --g cross-env
```

Best,
Manu

**Comment by hwang12345** [comment] 2018-05-15 13:57
i got the trouble too,but i do not konw where is the start script

**Comment by hwang12345** [comment] 2018-05-15 14:00
hello @marciandmnd ,
i got the trouble too today,but,i do not know where is the start script？

**Comment by hwang12345** [comment] 2018-05-16 02:01
@EINazare 
I changed the start script like this   "start": "cross-env NODE_ENV=./src react-scripts start",but it do not work .

**Comment by EINazare** [comment] 2018-05-16 05:48
Hello @hwang12345 

And thank you for your interest in using our product.
You also need to install cross-env globally:
```
npm install --g cross-env
```

Best,
Manu

**Comment by hwang12345** [comment] 2018-05-17 01:17
@EINazare 
i had install the cross-env but i also didn't work.And there is anthor problem ./src/layouts/Dashboard/Dashboard.jsx
Module not found: Can't resolve 'components' in 'D:\meteor+react\material-dashboard-react-master\src\layouts\Dashboard'

**Comment by EINazare** [comment] 2018-05-17 06:03
@hwang12345 ,

I honestly do not know what to tell you then. It is kind of strange. I've installed and started the app on a windows, and everything works fine on our machines (windows and mac).
You could try and install the latest `NodeJS` and `npm`, maybe this is the problem.
If that does not do the trick, than you should change all relative paths to absolute ones.

Best,
Manu

**Comment by chapma26** [comment] 2018-05-21 22:39
I can confirm this, too. I cloned the repo, npm install, and got the same error. Found this thread and added cross-env globally and set NODE_ENV and it's still broke. Giving up. Ubuntu 16, npm 6.0.1, node 8.11.1.

**Comment by Miskamyasa** [comment] 2018-06-19 20:10
why you can`t just write '../assets... etc?

**Comment by K-A124** [comment] 2018-07-02 09:44
"start": "cross-env NODE_ENV=./src react-scripts start" won't work because you have changed NODE_PATH to NODE_ENV.
Try - "start": "cross-env NODE_PATH=./src react-scripts start" - that's what worked for me.

**Comment by EINazare** [comment] 2018-07-02 10:16
@hwang12345 please see what @K-A124 said.

**Comment by ascooper57** [comment] 2018-10-05 05:54
Ok, I have the solution:

if NODE_PATH= is exported in ~/.bash_profile then its value overrides NODE_PATH= in the .env file.

So I modified my ~/.bash_profile

$ env
NODE_PATH=./src:/usr/local/lib/node_modules:/usr/local/lib/node

The .env file is not necessary via this solution. You can close this issue.

**Closed** 2019-01-18 15:52 UTC
Labels: enhancement, help wanted

**Comment by manpreetsingh3215** [comment] 2019-05-23 05:29
you can also create a new file in the root directory in the project named as .env and write 
 `NODE_PATH=./src` in it

**Comment by EINazare** [comment] 2019-05-23 07:37
A better solution is to create a jsconfig.json file with this code inside it:
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "*": ["src/*"]
    }
  }
}
```
All of our React products will have this file in the next updates.

Best,
Manu
ReactJS Developer

**Comment by sagarteria** [comment] 2019-06-26 20:57
> Hello @marciandmnd ,
> 
> You can solve this issue by changing the start script from:
> 
> ```
> "start": "react-scripts start",
> ```
> 
> to
> 
> ```
> "start": "NODE_PATH=./src react-scripts start",
> ```
> 
> and also you will need to install cross-env globally on your machine
> 
> ```
> npm install --g cross-env
> ```
> 
> Best,
> Manu

worked for me

**Comment by lbourbon** [comment] 2020-09-24 15:35
Important warning: Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.
