### ISSUE TITLE
[Bug] building the project without serve -s build

### ISSUE THREAD

**Issue by MehdiAghighi** [creativetimofficial/material-dashboard-react#124] opened 2020-06-13 12:01 UTC
### What is your enhancement?
i am using a cpanel host and i want to have a direct request to index.html from build folder and i can't use serve -s build for a server on port 5000.

i want the requests coming to folder where index.html is in, to use index.html and the file serve that.
is it possible ?

**Comment by MehdiAghighi** [comment] 2020-06-13 12:12
![image](https://user-images.githubusercontent.com/34032643/84568445-ca5bcb80-ad94-11ea-9ed4-2b5dff315c40.png)

i get these errors when i upload build folder into my shared hosting and blank screen shows up

**Comment by EINazare** [comment] 2020-06-13 15:08
Hello there, @MehdiAghighi ,

Duplicate of both #86 and #111 .

Best,
Manu

**Closed** 2020-06-13 15:09 UTC
Labels: duplicate
